server:
  port: 9102
  error:
    whitelabel:
      enabled: false

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 87654321
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # 确保地址正确
        namespace: dev
  #        username: nacos              # 如有需要，添加认证信息
  #        password: nacos
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        id-type: auto
        logic-delete-field: deleted
        logic-delete-value: 1
        logic-not-delete-value: 0
jwt:
  secret: user_service_secret_key
  expire: 86400000  # 24h

logging:
  level:
    com.universe.user: DEBUG
    org.apache.shiro: DEBUG
    org.springframework.web: DEBUG
fegin:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: full
        retryer:
          period: 100
          max-period: 1000
          max-attempts: 3
    movie-service:
      connect-timeout: 5000
      read-timeout: 5000
  httpclient:
      enabled: true
      max-connections: 200
      max-connections-per-route: 20

  logging:
    level:
      com.universe.user.feign: DEBUG
      com.universe.user: INFO
