server:
  port: 9103
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: movie-service
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

  datasource:
    url: jdbc:mysql://localhost:3306/movie_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 87654321
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # 确保地址正确
  #        username: nacos              # 如有需要，添加认证信息
  #        password: nacos
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


